version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3

executors:
  base:
    docker:
      - image: cimg/base:current
  python:
    docker:
      - image: cimg/python:3.14

jobs:
  setup-workspace:
    executor: base
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: [.]
  run-lint:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run: uv sync
      - run: uv run pylint *.py
  upload-coverage:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run: uv sync
      - run: |
          uv run pytest test_generate.py --cov
          uv run coverage xml
      - codecov/upload

workflows:
  code-analysis:
    jobs:
      - setup-workspace
      - run-lint:
          requires: [setup-workspace]
      - upload-coverage:
          requires: [setup-workspace]
